apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: inference-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: inference
        static_configs:
          - targets: ["inference.inference-system.svc.cluster.local:8001"]
      - job_name: dispatcher
        static_configs:
          - targets: ["dispatcher.inference-system.svc.cluster.local:8002"]
      - job_name: loadtester
        static_configs:
          - targets: ["loadtester.inference-system.svc.cluster.local:8003"]

