FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir aiohttp==3.9.5 prometheus_client==0.20.0 uvloop==0.19.0

COPY src/dispatcher ./dispatcher
ENV PYTHONPATH=/app

EXPOSE 8002
CMD ["python", "-m", "dispatcher.app"]
